market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"


urlpatterns = [
    path('userregistations',UserRegistations.as_view(),name="user_registations"),
    path('login/',Login.as_view(),name="login"),
    path('logout',Logout.as_view(),name='logout'),

#------------------------------- Work --------------------------

    path('',Home.as_view(),name="home"),
    path('search',SearchProduct.as_view(),name = "search"),
    path('item_detail/<int:pk>',PorductDetail.as_view(),name="item_detail"),
    path('addtocart/<int:pk>',AddToCart.as_view(),name="addtocart"),
    path('order_sumary/',OrderSumary.as_view(),name="order_sumary"),
    path('remove_item/<int:pk>',RemoveItemQty.as_view(),name="remove_item"),
    path('remove/<int:pk>',RemoveItem.as_view(),name="remove"),
    path('checkout',Checkout.as_view(),name = 'checkout'),
    path('update/<int:pk>',UpdateAddress.as_view(),name="update"),
    path('deleteaddress/<int:pk>',DeleteAddress.as_view(),name="deleteadress"),
    path('payment',PaymentView.as_view(),name="payment"),
    path('myorder',MyOrder.as_view(),name='myorder'),


    #---------------------------- Owner --------------------------------

    path('dashaboard',Dashaboard.as_view(),name="dashaboard"),
    path('requestorder',RequestForOrder.as_view(),name="request_order"),
    path('aproveorder/<int:pk>',AproveOrder.as_view(),name="aproveorder"),
    path('additem',AddItem.as_view(),name='additem'),
    path('allitem',AllItem.as_view(),name = 'allitem'),
    path('allorder',AllOrder.as_view(),name = 'allorder'),
    path('deleteitem/<int:pk>',DeleteItem.as_view(),name = 'deleteitem'),
    path('addbrand',AddBrand.as_view(),name = 'addbrand'),
    path('addcategory',AddCategory.as_view(),name = "addcategory"),
    path('allbrand',AllBrand.as_view(),name = "allbrand"),
    path('allcategory',AllCategory.as_view(),name = "allcategory"),
    path('deletebrand/<int:pk>',DeleteBrand.as_view(),name = 'deletebrand'),
    path('deletecategory/<int:pk>',DeleteCategory.as_view(),name = 'deletecategory'),

]

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #227093">
    <a class="navbar-brand ml-5" href="{% url 'shop:home' %}"><b>MARKET</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <form class="form-inline ml-5" action="{% url 'shop:search' %}" method="get">
    <input class="form-control mr-sm-2 ml-5" name="search"  placeholder="Search Product"  size="60xp">
    <button class="btn my-2 my-sm-0 pb-2" type="submit" style="margin-left: -80px;">Search</button>
  </form>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">

        <li class="nav-item active">
            <a class="nav-link mr-3" href="{% url 'shop:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
             <li class="nav-item dropdown mr-3">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   <i class="fas fa-cart-plus ml-2 mr-2 text-warning"></i> {{ user }}
                  </a>
                  <ul class="dropdown-menu mt-2 mr-3" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'shop:order_sumary' %}">Order Summary</a></li>
                    <li><a class="dropdown-item" href="{% url 'shop:myorder' %}">My Order</a></li>
                  </ul>
              </li>



             <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
             </li>

        {% else %}
            <li class="nav-item dropdown mr-3">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    User
                  </a>
                  <ul class="dropdown-menu mt-2 mr-3" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'shop:user_registations' %}">Signup</a></li>
                    <li><a class="dropdown-item" href="{% url 'shop:login' %}">Login</a></li>
                  </ul>
              </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:login' %}">Admin Login</a></li>

        {% endif %}

    </ul>
  </div>
</nav>

{% block content %}

{% endblock %}




<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


</body>
</html>

templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid mt-1 p-0">
<div class="row no-gutters">
    {% for foo in items %}
    <div class="col-lg-3 ml-2">
        <div class="card">
            <div class="card-body">
                <img src="{{ foo.img_one.url }}" alt="" class="card-img-top mb-4" height="300">
                <h5 class="display-5 ml-2">Title : {{ foo.title }}</h5>
                <h5 class="display-5 ml-2">Brand : {{ foo.brand.brand_name }}</h5>
                <h5 class="display-5 ml-2">Price : {{ foo.price }}</h5>
                <h5 class="display-5 ml-2">Discount : {{ foo.discoutn_price }}%</h5>
                <a href="{% url 'shop:item_detail' foo.item_id %}" class="btn btn-primary ml-5 mt-3">Bye Now</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}

templates/main/item_detail.html
{% extends 'main/base.html' %}


{% block content %}
 {% load static %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card border-0 shadow-sm">
                    <div class="card-body">
                         <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                             <div class="carousel-inner"><div class="carousel-item active">
                                 <img src="{{ product.img_one.url }}" class="d-block w-100 card-img-top" alt="" height="400">
                             </div>{% if product.img_two %}
                                 <div class="carousel-item">
                                     <img src="{{ product.img_two.url }}" class="d-block w-100 card-img-top" alt="" height="400">
                                 </div>
                             {% else %}
                                 <div class="carousel-item">
                                     <img src="{% static 'demo.png' %}" class="d-block w-100 card-img-top" alt="img not avalable" height="400">
                                 </div>
                             {% endif %}
                                 {% if product.img_three %}<div class="carousel-item">
                                     <img src="{{ product.img_three.url }}" class="d-block w-100 card-img-top" alt=""height="400">
                                 </div>{% else %}<div class="carousel-item">
                                     <img src="{% static 'demo.png' %}" class="d-block w-100 card-img-top" alt="image not avalable" height="400">
                                 </div>
                                 {% endif %}
                                 {% if product.img_four %}<div class="carousel-item">
                                     <img src="{{ product.img_four.url }}" class="d-block w-100 card-img-top" height="400" alt="">
                                 </div>{% else %}<div class="carousel-item">
                                     <img src="{% static 'demo.png' %}" class="d-block w-100 card-img-top" alt="image not avalable" height="400">
                                 </div>
                                 {% endif %}
                                 {% if product.img_five %}<div class="carousel-item">
                                     <img src="{{ product.img_five.url }}" class="d-block w-100 card-img-top" alt="" height="400">
                                 </div>
                                 {% else %}
                                     <div class="carousel-item">
                                     <img src="{% static 'demo.png' %}" class="d-block w-100 card-img-top" alt="image not avalable" height="400">
                                 </div>
                                 {% endif %}
                             </div>

                             <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                             <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                             <span class="sr-only">Previous</span>
                             </a><a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                 <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                 <span class="sr-only">Next</span>
                             </a>
                         </div>

                        <div class="mt-3 ml-4">
                            <h5 class="display-5 mt-1">Title : {{ product.title }}</h5>
                            <h5 class="display-5 mt-1">Brand : {{ product.brand }}</h5>

                            {% if product.discoutn_price %}
                                    <p>
                                    <span>Price : </span>
                                    <del>Rs. {{ product.price }}</del><span class="ml-2 text-success">, Rs.{{ product.item_discount }}</span>
                                    </p>
                            {% else %}
                                    <p>{{ product.price }}</p>
                            {% endif %}

                            <p class="small">Discription : {{ product.discription }}</p>

                            <a href="{% url 'shop:addtocart' product.item_id %}" class="btn btn-warning  mt-3">Add To Cart</a>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/main/login.html
{% extends 'main/base.html' %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-6 mx-auto mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="display-5 text-success text-center"><i><b>Login</b></i></h5>
                <form action="{% url 'shop:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>UserName</label>
                        <input type="email" class="form-control" placeholder="Username" name="username">
                    </div>

                    <div class="form-group">
                        <label>UserName</label>
                        <input type="password" class="form-control" placeholder="Username" name="password">
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-block">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/main/signup.html
{% extends 'main/base.html' %}

{% block content %}
    {% load crispy_forms_tags %}
<div class="container">
<div class="row">
    <div class="col-lg-6 mx-auto mt-3">
        <div class="card">
            <div class="card-body shadow-sm border-0">
                <h5 class="display-5 text-center text-success mb-4"><i><b>User Registations</b></i></h5>
                <form action="{% url 'shop:user_registations' %}" method="post">
                    {% csrf_token %}
                    <table class="table">
                        {{ form|crispy }}
                    </table>
                    <input type="submit" class="btn btn-success btn-block">
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}