market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"


urlpatterns = [
    path('userregistations',UserRegistations.as_view(),name="user_registations"),
    path('login/',Login.as_view(),name="login"),
    path('logout',Logout.as_view(),name='logout'),

#------------------------------- Work --------------------------

    path('',Home.as_view(),name="home"),
    path('search',SearchProduct.as_view(),name = "search"),
    path('item_detail/<int:pk>',PorductDetail.as_view(),name="item_detail"),
    path('addtocart/<int:pk>',AddToCart.as_view(),name="addtocart"),
    path('order_sumary/',OrderSumary.as_view(),name="order_sumary"),
    path('remove_item/<int:pk>',RemoveItemQty.as_view(),name="remove_item"),
    path('remove/<int:pk>',RemoveItem.as_view(),name="remove"),
    path('checkout',Checkout.as_view(),name = 'checkout'),
    path('update/<int:pk>',UpdateAddress.as_view(),name="update"),
    path('deleteaddress/<int:pk>',DeleteAddress.as_view(),name="deleteadress"),
    path('payment',PaymentView.as_view(),name="payment"),
    path('myorder',MyOrder.as_view(),name='myorder'),


    #---------------------------- Owner --------------------------------

    path('dashaboard',Dashaboard.as_view(),name="dashaboard"),
    path('requestorder',RequestForOrder.as_view(),name="request_order"),
    path('aproveorder/<int:pk>',AproveOrder.as_view(),name="aproveorder"),
    path('additem',AddItem.as_view(),name='additem'),
    path('allitem',AllItem.as_view(),name = 'allitem'),
    path('allorder',AllOrder.as_view(),name = 'allorder'),
    path('deleteitem/<int:pk>',DeleteItem.as_view(),name = 'deleteitem'),
    path('addbrand',AddBrand.as_view(),name = 'addbrand'),
    path('addcategory',AddCategory.as_view(),name = "addcategory"),
    path('allbrand',AllBrand.as_view(),name = "allbrand"),
    path('allcategory',AllCategory.as_view(),name = "allcategory"),
    path('deletebrand/<int:pk>',DeleteBrand.as_view(),name = 'deletebrand'),
    path('deletecategory/<int:pk>',DeleteCategory.as_view(),name = 'deletecategory'),

]

templates/owner/addbrand.html
{% extends 'owner/base.html' %}


{% block content %}
    {% load crispy_forms_tags %}
        <div class="container mt-4">
        <div class="row">
            <div class="col-lg-6 mx-auto mt-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="display-5 text-center text-success"><b><i>Add Brand</i></b></h5>
                        <form action="{% url 'shop:addbrand' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table class="table">
                                {{ forms|crispy }}
                            </table>
                            <input type="submit" class="btn btn-success btn-block">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>


{% endblock %}

templates/owner/addcategory.html
{% extends 'owner/base.html' %}


{% block content %}
    {% load crispy_forms_tags %}
        <div class="container mt-4">
        <div class="row">
            <div class="col-lg-6 mx-auto mt-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="display-5 text-center text-success"><b><i>Add Category</i></b></h5>
                        <form action="{% url 'shop:addcategory' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table class="table">
                                {{ form|crispy }}
                            </table>
                            <input type="submit" class="btn btn-success btn-block">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>


{% endblock %}

templates/owner/additem.html
{% extends 'owner/base.html' %}


{% block content %}
    {% load crispy_forms_tags %}
<div class="container">
<div class="row">
    <div class="col-lg-8 mx-auto mt-2">
        <div class="card">
            <div class="card-body">
                <h5 class="display-5 text-center text-success mt-1 mb-3" ><b><i>Add Item</i></b></h5>
                <form action="{% url 'shop:additem' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        {{ form|crispy }}
                    </table>
                    <input type="submit" class="btn btn-success btn-block">
                </form>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/owner/all_brand.html
{% extends 'owner/base.html' %}


{% block content %}
    <div class="container ">
    <div class="row">
        <div class="col-lg-6 mx-auto mt-4">
            <div class="card">
                <div class="card">
                    <table class="table">
                        <tr>
                            <td>Brand Name</td>
                            <td>Action</td>
                        </tr>

                        {% for x in allbrand %}
                            <tr>
                                <td>{{ x.brand_name }}</td>
                                <td><a href="{% url 'shop:deletebrand' x.brand_id %}" class="btn btn-danger">Delete</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/owner/all_category.html
{% extends 'owner/base.html' %}


{% block content %}
    <div class="container mt-4">
    <div class="row">
        <div class="col-lg-6 mx-auto mt-4">
            <div class="card">
                <div class="card">
                    <table class="table">
                        <tr>
                            <td>Category Name</td>
                            <td>Action</td>
                        </tr>

                        {% for x in allcategory %}
                            <tr>
                                <td>{{ x.title }}</td>
                                <td><a href="{% url 'shop:deletecategory' x.category_id %}" class="btn btn-danger">Delete</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/owner/all_item.html
{% extends 'owner/base.html' %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-10 mx-auto mt-3">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Pro Img</td>
                        <td>Pro Name</td>
                        <td>Brand</td>
                        <td>Category</td>
                        <td>Price</td>
                        <td>Discount Price</td>
                        <td>Action</td>
                    </tr>
                    {% for x in item %}
                        <tr>
                            <td><img src="{{ x.img_one.url }}" alt=""  style="height:100px;width:100px;border-radius:30px;"></td>
                             <td>{{ x.title }}</td>
                             <td>{{ x.brand }}</td>
                             <td>{{ x.category }}</td>
                             <td>{{ x.price }}</td>
                             <td>{{ x.discoutn_price }}</td>
                            <td><a href="{% url 'shop:deleteitem' x.item_id %}" class="btn btn-danger">Delete</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/owner/all_order.html
{% extends 'owner/base.html' %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-10 mx-auto mt-3">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Pro Img</td>
                        <td>Pro Name</td>
                        <td>User</td>
                        <td>Email</td>
                    </tr>
                    {% for x in allorder %}
                        <tr>
                            <td><img src="{{ x.items.itme.img_one.url  }}" alt="" ></td>
                            <td>{{ x.items.itme.title  }}</td>
                            <td>{{ x.user }}</td>
                            <td>{{ x.user.email }}</td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/owner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #227093">
    <a class="navbar-brand ml-5" href=""><b>MARKET</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated %}
             <li class="nav-item">
                <a class="btn btn-danger mr-5" href="{% url 'shop:logout' %}">Logout</a>
             </li>
        {% endif %}

    </ul>
  </div>
</nav>


<div class="container-fluid p-0">
    <div class="row no-gutters">
        <div class="col-lg-3">
            <div class="list-group">
                <a href="{% url 'shop:dashaboard' %}" class="list-group list-group-item list-group-item-action">Dashaboard</a>
                <a href="{% url 'shop:addcategory' %}" class="list-group list-group-item list-group-item-action">Add Category</a>
                <a href="{% url 'shop:addbrand' %}" class="list-group list-group-item list-group-item-action">Add Brand</a>
                <a href="{% url 'shop:additem' %}" class="list-group list-group-item list-group-item-action">Add Item</a>
                <a href="{% url 'shop:allitem' %}" class="list-group list-group-item list-group-item-action">All Item</a>
                <a href="{% url 'shop:allbrand' %}" class="list-group list-group-item list-group-item-action">All Brand</a>
                <a href="{% url 'shop:allcategory' %}" class="list-group list-group-item list-group-item-action">All Category</a>
                <a href="{% url 'shop:request_order' %}" class="list-group list-group-item list-group-item-action">Request Order</a>
                <a href="{% url 'shop:allorder' %}" class="list-group list-group-item list-group-item-action">Order</a>
            </div>
        </div>
        <div class="col-lg-9">{% block content %} {% endblock %}</div>
    </div>
</div>




</body>
</html>

templates/owner/dashaboard.html
{% extends 'owner/base.html' %}


{% block content %}
    <div class="container mt-2">
    <div class="row">
        <div class="col-lg-5 mx-auto mt-3">
            <div class="card">
                <div class="card-body shadow-sm border-0">
                    <h5 class="text-center text-success">All Request Order</h5>
                    <h5 class="text-center mt-2">{{ all_request_order }}</h5>
                </div>
            </div>
        </div>
        <div class="col-lg-5 mx-auto  mt-3">
            <div class="card">
                <div class="card-body shadow-sm border-0">
                    <h5 class="text-center text-success">All  Order</h5>
                    <h5 class="text-center mt-2">{{ all_order }}</h5>
                </div>
            </div>
        </div>
        <div class="col-lg-5 mx-auto  mt-3">
            <div class="card">
                <div class="card-body shadow-sm border-0">
                    <h5 class="text-center text-success">all Add Product</h5>
                    <h5 class="text-center mt-2">{{ all_add_item }}</h5>
                </div>
            </div>
        </div>

        <div class="col-lg-5 mx-auto  mt-3">
            <div class="card">
                <div class="card-body shadow-sm border-0">
                    <h5 class="text-center text-success">all Brand</h5>
                    <h5 class="text-center mt-2">{{ allbrand }}</h5>
                </div>
            </div>
        </div>

        <div class="col-lg-5  mt-3 mx-auto">
            <div class="card">
                <div class="card-body shadow-sm border-0">
                    <h5 class="text-center text-success">all Category</h5>
                    <h5 class="text-center mt-2">{{ allcategory }}</h5>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/owner/order_request.html
{% extends 'owner/base.html' %}


{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-10 mx-auto mt-3">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Pro Img</td>
                        <td>Pro Name</td>
                        <td>User</td>
                        <td>Email</td>
                        <td>Action</td>
                    </tr>
                    {% for x in request_order %}
                        <tr>
                             <td><img src="{{ x.items.itme.img_one.url  }}" alt="" ></td>
                             <td>{{ x.items.itme.title  }}</td>
                             <td>{{ x.user }}</td>
                             <td>{{ x.user.email }}</td>
                            <td><a href="{% url 'shop:aproveorder' x.order_id %}" class="btn btn-success">Aprove</a></td>
                        </tr>

                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}