market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"


urlpatterns = [
    path('userregistations',UserRegistations.as_view(),name="user_registations"),
    path('login/',Login.as_view(),name="login"),
    path('logout',Logout.as_view(),name='logout'),

#------------------------------- Work --------------------------

    path('',Home.as_view(),name="home"),
    path('search',SearchProduct.as_view(),name = "search"),
    path('item_detail/<int:pk>',PorductDetail.as_view(),name="item_detail"),
    path('addtocart/<int:pk>',AddToCart.as_view(),name="addtocart"),
    path('order_sumary/',OrderSumary.as_view(),name="order_sumary"),
    path('remove_item/<int:pk>',RemoveItemQty.as_view(),name="remove_item"),
    path('remove/<int:pk>',RemoveItem.as_view(),name="remove"),
    path('checkout',Checkout.as_view(),name = 'checkout'),
    path('update/<int:pk>',UpdateAddress.as_view(),name="update"),
    path('deleteaddress/<int:pk>',DeleteAddress.as_view(),name="deleteadress"),
    path('payment',PaymentView.as_view(),name="payment"),
    path('myorder',MyOrder.as_view(),name='myorder'),


    #---------------------------- Owner --------------------------------

    path('dashaboard',Dashaboard.as_view(),name="dashaboard"),
    path('requestorder',RequestForOrder.as_view(),name="request_order"),
    path('aproveorder/<int:pk>',AproveOrder.as_view(),name="aproveorder"),
    path('additem',AddItem.as_view(),name='additem'),
    path('allitem',AllItem.as_view(),name = 'allitem'),
    path('allorder',AllOrder.as_view(),name = 'allorder'),
    path('deleteitem/<int:pk>',DeleteItem.as_view(),name = 'deleteitem'),
    path('addbrand',AddBrand.as_view(),name = 'addbrand'),
    path('addcategory',AddCategory.as_view(),name = "addcategory"),
    path('allbrand',AllBrand.as_view(),name = "allbrand"),
    path('allcategory',AllCategory.as_view(),name = "allcategory"),
    path('deletebrand/<int:pk>',DeleteBrand.as_view(),name = 'deletebrand'),
    path('deletecategory/<int:pk>',DeleteCategory.as_view(),name = 'deletecategory'),

]

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #227093">
    <a class="navbar-brand ml-5" href="{% url 'shop:home' %}"><b>MARKET</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'shop:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}

              <li class="nav-item dropdown mr-3">

                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   <i class="fas fa-cart-plus ml-2 mr-2 text-warning"></i>{{ user }}
                  </a>
                  <ul class="dropdown-menu mt-2 mr-3" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'shop:order_sumary' %}">Order Summary</a></li>
                    <li><a class="dropdown-item" href="{% url 'shop:myorder' %}">My Order</a></li>
                  </ul>
              </li>

             <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
             </li>

        {% else %}
         <li class="nav-item">
             <a class="nav-link" href=""><i class="fas fa-cart-plus" style="size:20px"></i></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:user_registations' %}">Registation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
        </li>

        {% endif %}

    </ul>
  </div>
</nav>


<div class="container-fluid p-0">
    <div class="row no-gutters">
        <div class="col-lg-12">{% block content %} {% endblock %}</div>
    </div>
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>




</body>
</html>

templates/users/checkout.html
{% extends 'users/base.html' %}


{% block content %}
    {% load crispy_forms_tags %}
    <div class="container-fluid mt-2">
        <div class="row">
          <div class="col-lg-12">
                <div class="row">
                    {% for x in address %}
                    <div class="col-lg-4">
                        <div class="card bg-secondary text-white">
                            <div class="card-body">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <p>Name : {{ x.name }}</p>
                                    <p>Contact : {{ x.contact }}</p>
                                    <p>Email : {{ x.email }}</p>
                                    <p>Address : {{ x.city }} , {{ x.address }}</p>
                                    <p>Landmark : {{ x.landmark }}</p>
                                    <input  type="hidden"  name="save_address" value="{{ x.address_id }}">
                                    <input type="submit" class="btn btn-warning " value="Deliver to Address">
                                </form>
                                <span>
                                    <a href="{% url 'shop:update' x.address_id %}" class="btn btn-primary mt-2">Update</a>
                                    <a href="{% url 'shop:deleteadress' x.address_id %}" class="btn btn-danger mt-2">Delete</a>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>


              <h4 class="display-4 mt-3 mb-2 text-center text-uppercase text-success"><b>Add New Address</b></h4>
              <div class="row">
                  <div class="col-lg-8 mx-auto">
                            <div class="card">
                                <div class="card-body">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <table class="table">
                                            {{ forms|crispy }}
                                        </table>
                                        <input type="submit" class="btn btn-success btn-block">
                                    </form>
                                </div>
                            </div>
                      </div>
                 </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/my_order.html
{% extends 'users/base.html' %}


{% block content %}
    <div class="container mt-2">
    <div class="row">

    {% for main  in order %}

        <div class="col-lg-10 mx-auto">
            {% for o in main.items.all %}
        <div class="card mb-3">
        <div class="card-header">
            <span class="float-left"> Order Id: 00{{ main.order_id }}000000000000000</span>
            <span class="float-right">Order Date:{{ main.order_date }}</span>
        </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-3">
                        <img src="{{ o.itme.img_one.url }}" alt="" class="card-img-top">
                    </div>
                    <div class="col-lg-9">
                        <h2>{{ o.itme.title }}</h2>
                        <h2>{{ o.itme.brand.brand_name }}</h2>
                        <h5 class="display-5">Qty : {{ o.qty }}</h5>


                    <p>
                        {% if o.itme.discoutn_price %}
                            <del><span class="small">₹ {{ o.get_total_price }}</span></del>
                            <span class="small text-success">₹ {{ o.get_discount_price }}</span>
                        {% else %}
                            <span class="small font-weight-bold">₹ {{ o.get_total_price }}</span>
                        {% endif %}
                    </p>

                    {% if main.status is  True %}
                        <h5 class="display-5 text-success">STATUS : Deliver</h5>
                        {% else %}
                        <h5 class="display-5 text-danger">STATUS : Not Deliver</h5>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
    {% endfor %}
    </div>

{% endblock %}

templates/users/order_summary.html
{% extends 'users/base.html' %}

{% block content %}
   <div class="container-fluid m-3 p-0">
        <div class="row no-gutters">
            {% for x in order.items.all %}
            <div class="col-lg-7 mr-auto mt-2">
                <div class="card">
                    <div class="card-body">
                        <div class="row no-gutters">
                            <div class="col-lg-4">
                                <div class="card border-0 shadow-sm">
                                    <img src="{{ x.itme.img_one.url }}" alt="" class="card-img-top">
                                </div>
                            </div>
                            <div class="col-lg-5 ml-5">
                                <h5 class="display-5"> Title : {{ x.itme.title }}</h5>
                                <h5 class="display-5"> Brand : {{ x.itme.brand.brand_name }}</h5>
                                <p>Qty: {{ x.qty }}</p>
                                {% if x.itme.discoutn_price %}
                                    <p><del>Rs. {{ x.get_total_price }}</del>
                                      <samp class="text-success">Rs.{{ x.get_discount_price }}</samp>
                                    </p>
                                 {% else %}
                                    <p>Rs.{{ x.get_total_price }}</p>
                                {% endif %}

                            <div>
                                <span><a href="{% url 'shop:addtocart' x.itme.item_id %}" class="btn btn-sm btn-success ml-1">+</a></span>
                                <span class=" ml-1 mr-1"><b>{{ x.qty }}</b></span>
                                <span><a href="{% url 'shop:remove_item' x.itme.item_id %}" class="btn btn-danger btn-sm">-</a></span><br><br>
                                <span><a href="{% url 'shop:remove' x.itme.item_id %}" class="btn btn-danger btn-sm">Delete</a></span>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           {% endfor %}

                <div class="col-lg-4 mx-auto">
                     <div class="card">
                         <div class="card-body">
                            <h5 class="display-5 mt-1 text-center">Total Amount : {{ order.get_total }}</h5>

                             <div class="row mt-3">
                                 <div class="col-lg-6 mx-auto "><a href="{% url 'shop:checkout' %}" class="btn btn-success ">Checkout</a></div>
                                 <div class="col-lg-6 mx-auto "><a href="{% url 'shop:home' %}" class="btn-primary btn ">Continue Shoping</a></div>
                             </div>
                         </div>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}

templates/users/payment.html
{% extends 'users/base.html' %}

{% block content %}
<div class="container mt-4">
<div class="row">
    <div class="col-lg-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form action="{% url 'shop:payment' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="radio" value="online" name="payment">
                        <label>Online</label>
                    </div>

                    <div class="form-group">
                        <input type="radio" value="cod" name="payment">
                        <label>Case On delavery</label>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/users/update_address.html
{% extends 'users/base.html' %}


{% block content %}
    {% load crispy_forms_tags %}
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h5 class="display-5 text-success text-center"><i>Update Address</i></h5>
                        <form action="" method="post">
                            {% csrf_token %}
                            <table class="table">
                                {{ form|crispy }}
                            </table>
                            <div class="form-group">
                                <input type="submit" class="btn btn-success btn-block form-control">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}